title: PubkeyAcademy
markdown: kramdown

# for atom feed
author:
  name: PubkeyAcademy
  email: pubkey@pubkey.academy

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
include: 
  - .well-known